### ISSUE TITLE
Email body as HTML

### ISSUE THREAD

**Issue by olimart** [olimart/yamail#11]
When I paste full page HTML it renders as garbage.

Since it contains html tags 
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" style="font-family:Helivetica;" ...```

maybe we need to render as iFrame.

**Comment by croko** [comment]
paste where?

**Comment by olimart** [comment]
in campaign body

**Comment by croko** [comment]
press button "source" and paste html
![screen shot 2015-04-28 at 20 08 09](https://cloud.githubusercontent.com/assets/333912/7375594/75173da2-ede2-11e4-93d6-950f97f01923.png)
