### ISSUE TITLE
Merge tags

### ISSUE THREAD

**Issue by olimart** [olimart/yamail#12]
Run `rake bs` then import file. Go to list merge tags. 

```
NoMethodError - undefined method `fetch' for nil:NilClass
```

**Comment by croko** [comment]
all works on my side. Attach your file pls

**Comment by croko** [comment]
![screen shot 2015-05-09 at 14 16 37](https://cloud.githubusercontent.com/assets/333912/7549968/74881984-f656-11e4-988a-0a6e325c9631.png)
![screen shot 2015-05-09 at 14 16 50](https://cloud.githubusercontent.com/assets/333912/7549969/7cd08676-f656-11e4-8cda-0182971cda2b.png)
![screen shot 2015-05-09 at 14 17 25](https://cloud.githubusercontent.com/assets/333912/7549970/84483fac-f656-11e4-8b5a-14e7ae1f0196.png)
![screen shot 2015-05-09 at 14 17 47](https://cloud.githubusercontent.com/assets/333912/7549971/8c98429c-f656-11e4-84a0-a4a55f142db9.png)
![screen shot 2015-05-09 at 14 18 59](https://cloud.githubusercontent.com/assets/333912/7549972/961d271a-f656-11e4-8216-07f44e7a528b.png)
![screen shot 2015-05-09 at 14 19 21](https://cloud.githubusercontent.com/assets/333912/7549973/9b35c55e-f656-11e4-8bcb-ab0ae8060eeb.png)
Looks like it works...
