### ISSUE TITLE
Liquidize campaign

### ISSUE THREAD

**Issue by olimart** [olimart/yamail#8]
when I visit campaign preview page, none of the liquidize tags are working.

**Comment by croko** [comment]
all works on my side
![screen shot 2015-04-28 at 14 47 43](https://cloud.githubusercontent.com/assets/333912/7368915/a5a114c0-edb5-11e4-8de9-5327ecdd27e8.png)
![screen shot 2015-04-28 at 14 47 01](https://cloud.githubusercontent.com/assets/333912/7368921/adeaecbe-edb5-11e4-83de-b9d9e120cbe2.png)
![screen shot 2015-04-28 at 14 42 46](https://cloud.githubusercontent.com/assets/333912/7368922/b5af09c6-edb5-11e4-9789-b65269556ce2.png)
![screen shot 2015-04-28 at 14 43 19](https://cloud.githubusercontent.com/assets/333912/7368925/bd2d3006-edb5-11e4-96af-5e9671381a13.png)

**Comment by olimart** [comment]
Whaooo. Now I see content although I didn't change anything.

**Comment by olimart** [comment]
ok I found what's wrong.
In campaign, change list for a manually imported list (you can test with test csv file).
If list does not have margin tags (in body), nothing is rendered. Same if you remove all merge tags.
